website/routes/parent.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, session
from flask_login import current_user
from website.routes.main import login_required
from website import app, db
from website.models import *
from website.forms import *
import decimal
import stripe

parent = Blueprint('parent', __name__)

@parent.route("/dashboard/parent", methods=['GET', 'POST'])
@login_required(role="parent")
def parent_dashboard():
    menus = FOOD_MENU.query.all()
    users = USER.query.all()
    trans = TRANSACTION.query.filter_by(PARENT_ID=current_user.id).all()
    transactions = sorted(trans, key=lambda x: x.DATE_TIME, reverse=True)
    loads = RELOAD.query.filter_by(PARENT_ID=current_user.id).all()
    reloads = sorted(loads, key=lambda x: x.DATE_TIME, reverse=True)
    foodorders = FOOD_ORDER.query.filter_by(PARENT_ID=current_user.id).all()
    orders = sorted(foodorders, key=lambda x: x.transaction.DATE_TIME if x.transaction else None, reverse=True)

    per_page = 5
    order_page = request.args.get('order_page', 1, type=int)
    start_order_index = (order_page - 1) * per_page
    end_order_index = start_order_index + per_page
    paginated_orders = orders[start_order_index:end_order_index]

    transaction_page = request.args.get('transaction_page', 1, type=int)
    start_transaction_index = (transaction_page - 1) * per_page
    end_transaction_index = start_transaction_index + per_page
    paginated_transactions = transactions[start_transaction_index:end_transaction_index]

    reload_page = request.args.get('reload_page', 1, type=int)
    start_reload_index = (reload_page - 1) * per_page
    end_reload_index = start_reload_index + per_page
    paginated_reloads = reloads[start_reload_index:end_reload_index]

    return render_template('parent/dashboard.html', users=users,orders=orders, transactions=transactions, reloads=reloads,menus=menus, per_page=per_page, paginated_orders=paginated_orders, paginated_transactions=paginated_transactions, paginated_reloads=paginated_reloads, order_page=order_page, transaction_page=transaction_page, reload_page=reload_page, total_orders=len(orders), total_transactions=len(transactions), total_reloads=len(reloads))

@parent.route("/foodmenu", methods=['GET', 'POST'])
@login_required(role="parent")
def parent_menu():
    form = CartForm()
    users = USER.query.all()
    menus = FOOD_MENU.query.all()
    students = STUDENT.query.all()
    return render_template('parent/foodmenu.html', users=users,menus=menus, students = students, form=form)

@parent.route("/cart", methods=['GET', 'POST'])
@login_required(role="parent")
def parent_cart():
    form = CartForm()
    users = USER.query.all()
    menus = FOOD_MENU.query.all()
    form.parent_id.data = current_user.id
    parent_id = form.parent_id.data
    balancedecimal = PARENT.query.filter_by(id=parent_id).with_entities(PARENT.EWALLET_BALANCE).all()
    balanceonedp= float(balancedecimal[0][0])
    balancefloat = float(balanceonedp)
    balance = "{:.2f}".format(balancefloat)

    import re
    if request.method == 'POST':
        for key, value in request.form.items():
            if key.startswith('menu_id_'):
                match = re.match(r'menu_id_(\d+)', key)
                if match:
                    index = match.group(1)
                    menu_id = request.form.get(f'menu_id_{index}')
                    day = request.form.get(f'Day_{index}')
                    student_id = request.form.get('StudentID')

                    if menu_id and day and student_id:
                        add_item = CART_ITEM(PARENT_ID=parent_id, MENU_ID=menu_id, STUDENT_ID=student_id, ORDER_PER_DAY=day)
                        with app.app_context():
                            db.session.add(add_item)
                            db.session.commit()
                            flash('Items added to cart!', 'success')
                    return redirect(url_for('parent.parent_cart'))
    
    cart_items = CART_ITEM.query.filter_by(PARENT_ID=parent_id).all()
    prices = {menu.id: menu.PRICE for menu in menus}
    total_price = sum(prices[cart_item.MENU_ID] for cart_item in cart_items)
    return render_template('parent/cart.html', users=users,form=form, parent_id=parent_id, menu_id=request.form.get('menu_id'), carts=cart_items, menus=menus,total_price=total_price,balance=balance)

@parent.route('/cart/delete/<int:cart_id>', methods=['POST'])
@login_required(role="parent")
def deleteCart(cart_id):
    deleteCart = CART_ITEM.query.get_or_404(cart_id)

    if request.method == 'POST':
        db.session.delete(deleteCart)
        db.session.commit()
        flash('Menu deleted!', 'success')
        return redirect(url_for('parent.parent_cart'))

    return redirect(url_for('parent.parent_cart'))

@parent.route('/cart/pay', methods=['POST'])
@login_required(role="parent")
def pay():
    parent_id = current_user.id
    menus = FOOD_MENU.query.all()
    cart_items = CART_ITEM.query.filter_by(PARENT_ID=parent_id).all()
    payment_time = datetime.now().replace(microsecond=0)
    
    prices = {menu.id: menu.PRICE for menu in menus}
    total_price = sum(prices[cart_item.MENU_ID] for cart_item in cart_items)

    current_parent = PARENT.query.filter_by(id=current_user.id).first()
    decimal_price = decimal.Decimal(total_price)
    
    print("cart_items:", cart_items)

    if not cart_items:
        flash('No items in the cart.', 'error')
    if current_parent.EWALLET_BALANCE >= total_price:
        current_parent.EWALLET_BALANCE -= decimal_price
        db.session.commit()
        for cart_item in cart_items:
            paid = TRANSACTION(
                PARENT_ID=cart_item.PARENT_ID,
                AMOUNT=total_price,
                DATE_TIME=payment_time
            )
        db.session.add(paid)
        db.session.commit()
        transactionid = TRANSACTION.query.filter_by(PARENT_ID=parent_id).order_by(TRANSACTION.DATE_TIME.desc()).first()
        for cart_item in cart_items:
                foodorder = FOOD_ORDER(
                    ORDER_DAY=cart_item.ORDER_PER_DAY,
                    REDEMPTION=False,
                    MENU_ID=cart_item.MENU_ID,
                    PARENT_ID=cart_item.PARENT_ID,
                    STUDENT_ID=cart_item.STUDENT_ID,
                    TRANSACTION_ID=transactionid.id
                    )
                db.session.add(foodorder)    
                db.session.delete(cart_item)
        db.session.commit()
        flash('Payment successful!', 'success')
    else:
        flash('Insufficient balance. Please reload your e-wallet.', 'error')

    return redirect(url_for('parent.parent_cart'))

def clear_reload_session():
    session.pop('reload_amount', None)
    session.pop('reload_init_datetime', None)
    session.pop('reload_session_id', None)
    session.pop('reload_completion_datetime', None)

@parent.route("/reload", methods=['GET', 'POST'])
@login_required(role="parent")
def parent_reload():
    current_parent = PARENT.query.filter_by(id=current_user.id).first()
    balance = current_parent.EWALLET_BALANCE

    clear_reload_session()
    reloadForm = ReloadForm()

    return render_template('parent/reload/reload.html', username=current_user.USERNAME, showBalance=True, balance=balance, reloadForm=reloadForm)

@parent.route("/reload/validate", methods=['GET', 'POST'])
@login_required(role="parent")
def reload_validate():
    if request.method == 'GET':
        return redirect('/404')

    reloadForm = ReloadForm()
    if reloadForm.validate_on_submit():
        session['reload_amount'] = reloadForm.amount.data
        session['reload_init_datetime'] = datetime.now().replace(microsecond=0)
        return redirect(url_for('parent.reload_confirm'), code=307)
    else:
        flash('Reload amount is minimum RM2 and maximum RM10,000', 'error')
        return redirect(url_for('parent.parent_reload'))


@parent.route("/reload/confirm", methods=['GET', 'POST'])
@login_required(role="parent")
def reload_confirm():
    if request.method == 'GET' or not session.get('reload_init_datetime'):
        return redirect(url_for('parent.parent_reload'))

    date_time = str(session['reload_init_datetime'])[:-6]
    amount = "{:.2f}".format(session['reload_amount'])

    return render_template("parent/reload/confirm.html", username=current_user.USERNAME, showDatetime=True, date_time=date_time, showAmount=True, amount=amount)

@parent.route('/reload/charge', methods=['GET', 'POST'])
@login_required(role="parent")
def reload_charge():
    if request.method == 'GET' or not session.get('reload_init_datetime'):
        return redirect(url_for('parent.parent_reload'))
    
    amount = session['reload_amount'] * 100.0 # amount is in cents
    checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    'price_data': {
                        'product_data': {
                            'name': 'LunchMate E-wallet Reload',
                        },
                        'unit_amount': int(amount), 
                        'currency': 'myr',
                    },
                    'quantity': 1,
                },
            ],
            payment_method_types=['card'],
            mode='payment',
            currency= 'myr',
            success_url=request.host_url + url_for('parent.reload_success_redirect', key=app.config['STRIPE_PUBLISHABLE_KEY']) + '?r=true',
            cancel_url=request.host_url + url_for('parent.reload_success_redirect', key=app.config['STRIPE_PUBLISHABLE_KEY']) + '?r=false',
        )
    session['reload_session_id'] = checkout_session.id

    return redirect(checkout_session.url)


@parent.route('/reload/success/<string:key>', methods=['GET', 'POST'])
@login_required(role="parent")
def reload_success_redirect(key):
    if key != app.config['STRIPE_PUBLISHABLE_KEY'] or not session.get('reload_session_id'):
        return redirect('/404')
    

website/templates/parent/cart.html
{% extends "base.html" %}
{% block title %}Cart Items{% endblock title %}
{% block content %}
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5 antialiased">
    <div class="mx-auto max-w-screen-xl px-4 lg:px-12 min-h-screen">
        <h3 class="text-xl font-bold dark:text-white text-center my-8">Cart</h3>
        <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            <div class="overflow-x-auto">
                <table id="orderTable" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-4 py-3">No.</th>
                            <th scope="col" class="px-4 py-3">Order Day</th>
                            <th scope="col" class="px-4 py-3">Student Name</th>
                            <th scope="col" class="px-4 py-3">Menu ID</th>
                            <th scope="col" class="px-4 py-3">Menu Set</th>
                            <th scope="col" class="px-4 py-3">Type</th>
                            <th scope="col" class="px-4 py-3">Description</th>
                            <th scope="col" class="px-4 py-3">Main Course</th>
                            <th scope="col" class="px-4 py-3">Beverage</th>
                            <th scope="col" class="px-4 py-3">Image</th>
                            <th scope="col" class="px-4 py-3">Price</th>
                            <th scope="col" class="px-4 py-3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="border-b dark:border-gray-700">
                            <!-- {{ form.csrf_token }}
                        {{ form.hidden_tag() }} -->
                            {% for cart in carts %}
                            <!-- <form method="post" action="{{ url_for('parent.parent_cart') }}" id="DeleteCartForm_{{ loop.index }}"> -->
                        <tr class="border-b dark:border-gray-700">
                            <th scope="row" data-cart-id="{{ cart.id }}"
                                class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{
                                loop.index }}
                                <input type="hidden" id="cart_id_{{ loop.index }}" name="cart_id_{{ loop.index }}"
                                    value="{{ cart.id }}_{{ loop.index }}">
                            </th>
                            <td class="px-4 py-3">{{ cart.ORDER_PER_DAY }}</td>
                            {% for user in users %}
                            {% if cart.STUDENT_ID == user.id%}
                            <td class="px-4 py-3">{{ user.FIRST_NAME }}</td>
                            <input type="hidden" name="cart.Studentid" value="{{ user.id }}" >
                            {% endif %}
                            {% endfor %}

                            <td class="px-4 py-3">{{ cart.MENU_ID }}</td>
                            {% for menu in menus %}
                            {% if cart.MENU_ID == menu.id%}

                            <td class="px-4 py-3">{{ menu.SET }}</td>
                            <td class="px-4 py-3">{{ menu.TYPE }}</td>
                            <td class="px-4 py-3">{{ menu.DESCRIPTION }}</td>
                            <td class="px-4 py-3">{{ menu.MAIN_COURSE.NAME }}</td>
                            <td class="px-4 py-3">{{ menu.BEVERAGE.NAME }}</td>
                            <td class="px-4 py-3">
                                <img class="w-20 h-20" src="{{ url_for('static', filename='menu_pics/' + menu.IMAGE) }}" alt="{{ menu.SET }} image">
                            </td>
                            <td class="px-4 py-3">{{ menu.PRICE }}</td>
                            {% endif %}
                            {% endfor %}
                            <td class="px-4 py-3">
                                <button type="button" data-modal-target="{{cart.id}}-deleteCartModal" data-modal-toggle="{{cart.id}}-deleteCartModal" class="py-2 px-6 flex items-center text-sm font-medium text-center text-white hover:text-red-600 focus:outline-none bg-red-600 rounded-lg border border-red-600 hover:bg-transparent hover:text-primary-700 dark:bg-red-600 dark:text-white dark:border-red-600 dark:hover:text-red-600 dark:hover:bg-transparent">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 -ml-0.5" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                                        </svg>
                                        Delete
                                    </button>
                                    <div id="{{cart.id}}-deleteCartModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                                        <div class="relative p-4 w-full max-w-md max-h-full">
                                            <div class="relative p-4 text-center bg-white rounded-lg shadow dark:bg-gray-800 sm:p-5">
                                                <button type="button" class="text-gray-400 absolute top-2.5 right-2.5 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="{{cart.id}}-deleteCartModal">
                                                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                                                    </svg>
                                                    <span class="sr-only">Close modal</span>
                                                </button>
                                                <svg class="text-gray-400 dark:text-gray-500 w-11 h-11 mb-3.5 mx-auto" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                                                </svg>
                                                <p class="mb-4 text-gray-500 dark:text-gray-300">Are you sure you want to delete this item?</p>
                                                <div class="flex justify-center items-center space-x-4">
                                                    <button data-modal-toggle="{{cart.id}}-deleteCartModal" type="button" class="py-2 px-3 text-sm font-medium text-gray-500 bg-white rounded-lg border border-gray-200 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-primary-300 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">No, cancel</button>
                                                    <form action="{{ url_for('parent.deleteCart', cart_id=cart.id)}}" method="post">
                                                        <button type="submit" class="py-2 px-3 text-sm font-medium text-center text-white bg-red-600 rounded-lg hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900">Yes, I'm sure</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </td>
                        </tr>
                        {% endfor %}
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr class="border-b dark:border-gray-700">
                            <td class="px-4 py-3 font-bold text-end" colspan="8">E-Wallet Balance: </td>
                            <td class="px-4 py-3 font-bold text-end">{{balance}}</td>
                            <td class="px-4 py-3 font-bold text-end">Total price: </td>
                            <td class="px-4 py-3 font-bold text-end">{{total_price}}</td>
                            <td class="px-4 py-3 text-end" colspan="2">
                                <form action="{{ url_for('parent.pay')}}" method="post">
                                    <button type="submit"
                                        class="py-2 px-6 flex items-center text-sm font-medium text-center text-white hover:text-blue-600 focus:outline-none bg-blue-600 rounded-lg border border-blue-600 hover:bg-transparent hover:text-primary-700 focus:ring-blue-600 dark:bg-blue-600 dark:text-white dark:border-blue-600 dark:hover:text-blue-600 dark:hover:bg-transparent">
                                        Pay</button>
                                </form>
                            </td>
                        </tr>
                    </tfoot>
                </table>

            </div>

        </div>
    </div>
</section>
{% endblock content %}

<script>
    function deleteCartItem(cartId, rowIndex) {
        document.getElementById('cart_id_' + rowIndex).value = cartId;
        document.getElementById('DeleteCartForm_' + rowIndex).submit();
    }
</script>

website/templates/parent/foodmenu.html
{% extends "base.html" %}
{% block title %}Food Menu{% endblock title %}
{% block content %}
<!-- Food Menu -->
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5 antialiased">
    <div class="mx-auto max-w-screen-xl px-4 lg:px-12 min-h-screen">
        <h3 class="text-xl font-bold dark:text-white text-center my-8">Food Menu</h3>
        <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                <div class="w-full md:w-1/2">
                    <form>
                        <label for="menu-search"
                            class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
                        <div class="relative w-full">
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                                    xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                        stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                                </svg>
                            </div>
                            <input type="search" id="menu-search"
                                class="block w-full p-3 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                placeholder="Search Food Menu ..." required>
                        </div>
                    </form>
                </div>
            </div>
            <div class="overflow-x-auto">
                <table id="menuTable" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-4 py-4">ID</th>
                            <th scope="col" class="px-4 py-3">Order Day</th>
                            <th scope="col" class="px-4 py-3">Menu</th>
                            <th scope="col" class="px-4 py-3">Price</th>
                            <th scope="col" class="px-4 py-3">Type</th>
                            <th scope="col" class="px-4 py-3">Description</th>
                            <th scope="col" class="px-4 py-3">Main Course</th>
                            <th scope="col" class="px-4 py-3">Beverage</th>
                            <th scope="col" class="px-4 py-3">Image</th>
                            <th scope="col" class="px-4 py-3">Student Name</th>
                            <th scope="col" class="px-4 py-3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{ form.csrf_token }}
                        {{ form.hidden_tag() }}
                        {% for menu in menus %}
                        {% if menu.VISIBILITY == 'public' %}
                        <form method="post" action="{{ url_for('parent.parent_cart') }}" id="cartForm_{{ loop.index }}">
                            <tr class="border-b dark:border-gray-700">
                                <th scope="row" data-menu-id="{{ menu.id }}"
                                    class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{
                                    loop.index }}
                                    <input type="hidden" id="menu_id_{{ loop.index }}" name="menu_id_{{ loop.index }}"
                                        value="{{ menu.id }}_{{ loop.index }}">
                                </th>

                                <td scope="px-4 py-3">
                                  
                                    <select id="Day_{{ loop.index }}" name="Day_{{ loop.index }}" class="text-white bg-blue-700 hover:bg-blue-800 font-sm rounded-lg text-sm px-1 py-1.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700">
                                        <option value="Monday">Monday</option>
                                        <option value="Tuesday">Tuesday</option>
                                        <option value="Wednesday">Wednesday</option>
                                        <option value="Thursday">Thursday</option>
                                        <option value="Friday">Friday</option>
                                    </select>

                                </td>
                                <td class="px-4 py-3">{{ menu.SET }}</td>
                                <td class="px-4 py-3">{{ menu.PRICE }}</td>
                                <td class="px-4 py-3">{{ menu.TYPE }}</td>
                                <td class="px-4 py-3">{{ menu.DESCRIPTION }}</td>
                                <td class="px-4 py-3">{{ menu.MAIN_COURSE.NAME }}</td>
                                <td class="px-4 py-3">{{ menu.BEVERAGE.NAME }}</td>
                                <td class="px-4 py-3">
                                    <img class="w-20 h-20" src="{{ url_for('static', filename='menu_pics/' + menu.IMAGE) }}" alt="{{ menu.SET }} image">
                                </td>
                                <td class="px-4 py-3 ">
                                    <select id="StudentID" name="StudentID" class="text-white bg-blue-700 hover:bg-blue-800 font-sm rounded-lg text-sm px-1 py-1.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700">
                                        {% for student in students %}
                                        {% for user in users %}
                                        {% if student.id == user.id%}
                                        <option value="{{ student.id }}">{{ user.FIRST_NAME }}</option>
                                        {% endif %}
                                        {% endfor %}
                                        {% endfor %}

                                    </select>
                                </td>
                                <td class="px-4 py-3">
                                    <button type="submit" onclick="setMenuIdAndDay('{{ menu.id }}', '{{ loop.index }}')"
                                        class="py-2 px-6 flex items-center text-sm font-medium text-center text-white hover:text-blue-600 focus:outline-none bg-blue-600 rounded-lg border border-blue-600 hover:bg-transparent hover:text-primary-700 focus:ring-blue-600 dark:bg-blue-600 dark:text-white dark:border-blue-600 dark:hover:text-blue-600 dark:hover:bg-transparent">
                                        Add
                                    </button>
                        </form>
                        </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>


<script>
    function setMenuIdAndDay(menuId, rowIndex) {
        var dayDropdown = document.getElementById('Day_' + rowIndex);
        var selectedDay = dayDropdown.value;
        if (!selectedDay) {
            selectedDay = dayDropdown.options[0].value;
        }

        document.getElementById('menu_id_' + rowIndex).value = menuId;
        document.getElementById('Day_' + rowIndex).value = selectedDay;

        document.getElementById('cartForm_' + rowIndex).submit();
    }

    document.addEventListener("DOMContentLoaded", function () {
        const menuSearch = document.getElementById("menu-search");
        const menutable = document.getElementById("menuTable");
        const menurows = menutable.getElementsByTagName("tr");
        searchListener(menuSearch, menurows, 7);
    });
</script>

{% endblock content %}