website/routes/main.py
from flask import Blueprint, render_template, url_for, flash, redirect, current_app, request
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message
from website import app, db, bcrypt, mail
from functools import wraps
from website.models import *
from website.forms import *
from PIL import Image
import secrets
import os

main = Blueprint('main', __name__)

def login_required(role="ANY"):
    def wrapper(fn):
        @wraps(fn)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
               return current_app.login_manager.unauthorized()
            if ((current_user.ROLE != role) and (role != "ANY")):
               return current_app.login_manager.unauthorized()      
            return fn(*args, **kwargs)
        return decorated_view
    return wrapper

def check_role(role="ANY"):
    if current_user.is_authenticated:
        if current_user.ROLE == 'parent':
            return redirect(url_for('parent.parent_dashboard'))
        elif current_user.ROLE == 'student':
            return redirect(url_for('student.student_dashboard'))
        elif current_user.ROLE == 'worker':
            return redirect(url_for('worker.worker_dashboard'))
        elif current_user.ROLE == 'admin':
            return redirect(url_for('admin.admin_dashboard'))
    return render_template('home.html')

@main.errorhandler(404)
def page_not_found(e):
    return render_template('error.html')

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/profile_pics', picture_fn)
    output_size = (125,125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)
    return picture_fn

@main.route("/login", methods=['GET', 'POST'])
def login():
    check_role()
    if current_user.is_authenticated:
        flash('User is already logged in', 'danger')
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = USER.query.filter_by(USERNAME=form.username.data).first()
        if user and bcrypt.check_password_hash(user.PASSWORD, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if user.ROLE == 'parent':
                return redirect(next_page) if next_page else redirect(url_for('parent.parent_dashboard'))
            elif user.ROLE == 'student':
                return redirect(next_page) if next_page else redirect(url_for('student.student_dashboard'))
            elif user.ROLE == 'worker':
                return redirect(next_page) if next_page else redirect(url_for('worker.worker_dashboard'))
            elif user.ROLE == 'admin':
                return redirect(next_page) if next_page else redirect(url_for('admin.admin_dashboard'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@main.route("/profile", methods=['GET', 'POST'])
@login_required(role="ANY")
def profile():
    users = USER.query.all()
    form = UpdateProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.IMAGE = picture_file
        current_user.USERNAME = form.username.data
        current_user.EMAIL = form.email.data
        current_user.FIRST_NAME = form.firstname.data
        current_user.LAST_NAME = form.lastname.data
        current_user.PHONE = form.phone.data
        if current_user.ROLE == 'parent':
            current_user.EWALLET_BALANCE = form.ewallet_balance.data
        for user in users:
            if user.USERNAME == form.username.data and user.id != current_user.id:
                flash('That username is taken. Please enter a different username.', 'danger')
                return redirect(url_for('main.profile'))
            elif user.EMAIL == form.email.data and user.id != current_user.id:
                flash('That email is taken. Please enter a different email.', 'danger')
                return redirect(url_for('main.profile'))
            elif user.PHONE == form.phone.data and user.id != current_user.id:
                flash('That phone is taken. Please enter a different phone number.', 'danger')
                return redirect(url_for('main.profile'))
        db.session.commit()
        flash('Your profile has been updated!', 'success')
        return redirect(url_for('main.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.USERNAME
        form.email.data = current_user.EMAIL
        form.firstname.data = current_user.FIRST_NAME
        form.lastname.data = current_user.LAST_NAME
        form.phone.data = current_user.PHONE
        image_file = url_for('static', filename='profile_pics/' + current_user.IMAGE)
        if current_user.ROLE == 'parent':
            current_parent = PARENT.query.filter_by(id=current_user.id).first()
            form.ewallet_balance.data = current_parent.EWALLET_BALANCE
            students = STUDENT.query.filter_by(PARENT1_ID=current_user.id).all() + STUDENT.query.filter_by(PARENT2_ID=current_user.id).all()
            return render_template('profile.html', title='Profile', image_file=image_file, form=form, students=students)
        elif current_user.ROLE == 'student':
            current_student = STUDENT.query.filter_by(id=current_user.id).first()
            form.status.data = current_student.STATUS
            parents = USER.query.filter(USER.id.in_([current_student.PARENT1_ID, current_student.PARENT2_ID])).all()
            return render_template('profile.html', title='Profile', image_file=image_file, form=form, parents=parents)
        elif current_user.ROLE == 'worker' or current_user.ROLE == 'admin':
            return render_template('profile.html', title='Profile', image_file=image_file, form=form)

def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request', sender='noreply@demo.com', recipients=[user.EMAIL])
    msg.body=f'''To reset your password, visit the following link:
{url_for('main.reset_token', token=token, _external=True)}

If you did not make this request then simply ignore this email and no change will be made.
    '''
    mail.send(msg)

@main.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    check_role()
    form = RequestResetForm()
    if form.validate_on_submit():
        user = USER.query.filter_by(EMAIL=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('main.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@main.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    check_role()
    user = USER.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token or expired token', 'warning')
        return redirect(url_for('main.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.PASSWORD = hashed_password
        print(user.PASSWORD)
        db.session.add(user)
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('main.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@main.route("/change_password", methods=['GET', 'POST'])
@login_required(role="ANY")
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.PASSWORD, form.old_password.data):
            if bcrypt.check_password_hash(current_user.PASSWORD, form.new_password.data):
                flash('New password cannot be the same as old password', 'danger')
            else:
                hashed_password = bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
                current_user.PASSWORD = hashed_password
                db.session.commit()
                flash('Your password has been updated!', 'success')
                return redirect(url_for('main.profile'))
        else:
            flash('Incorrect old password', 'danger')
    return render_template('change_password.html', title='Change Password', form=form)

website/templates/change_password.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock title %}
{% block content %}
<div class="flex flex-col items-center justify-center px-6 py-8 mx-auto h-screen lg:py-0">
    <a href="{{ url_for('main.home') }}" class="text-blue-700 mb-5 dark:text-white flex items-center space-x-3 rtl:space-x-reverse">
        <svg class="w-5 h-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
            <path d="M416 0C400 0 288 32 288 176V288c0 35.3 28.7 64 64 64h32V480c0 17.7 14.3 32 32 32s32-14.3 32-32V352 240 32c0-17.7-14.3-32-32-32zM64 16C64 7.8 57.9 1 49.7 .1S34.2 4.6 32.4 12.5L2.1 148.8C.7 155.1 0 161.5 0 167.9c0 45.9 35.1 83.6 80 87.7V480c0 17.7 14.3 32 32 32s32-14.3 32-32V255.6c44.9-4.1 80-41.8 80-87.7c0-6.4-.7-12.8-2.1-19.1L191.6 12.5c-1.8-8-9.3-13.3-17.4-12.4S160 7.8 160 16V150.2c0 5.4-4.4 9.8-9.8 9.8c-5.1 0-9.3-3.9-9.8-9L127.9 14.6C127.2 6.3 120.3 0 112 0s-15.2 6.3-15.9 14.6L83.7 151c-.5 5.1-4.7 9-9.8 9c-5.4 0-9.8-4.4-9.8-9.8V16zm48.3 152l-.3 0-.3 0 .3-.7 .3 .7z"/>
        </svg>
        <span class="self-center text-2xl font-semibold whitespace-nowrap">LunchMate</span>
    </a>
    <div class="w-full p-6 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md dark:bg-gray-800 dark:border-gray-700 sm:p-8">
        <h2 class="mb-1 text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
            Change Password
        </h2>
        <form method="POST" class="space-y-4 md:space-y-6" action="">
            {{ form.hidden_tag() }}
            <div>
                {{ form.old_password.label(class="block mb-1.5 text-sm font-medium text-gray-900 dark:text-white") }}
                {% if form.old_password.errors %}
                    {{ form.old_password(class="bg-gray-50 border-2 border-red-600 text-red-600 sm:text-sm rounded-lg focus:ring-red-900 focus:border-red-600 block w-full p-2.5") }}
                    <div class="text-red-600 mt-2">
                        {% for error in form.old_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.old_password(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500") }}
                {% endif %}
            </div>
            <div>
                {{ form.new_password.label(class="block mb-1.5 text-sm font-medium text-gray-900 dark:text-white") }}
                {% if form.new_password.errors %}
                    {{ form.new_password(class="bg-gray-50 border-2 border-red-600 text-red-600 sm:text-sm rounded-lg focus:ring-red-900 focus:border-red-600 block w-full p-2.5") }}
                    <div class="text-red-600 mt-2">
                        {% for error in form.new_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.new_password(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500") }}
                {% endif %}
            </div>
            <div>
                {{ form.confirm_new_password.label(class="block mb-1.5 text-sm font-medium text-gray-900 dark:text-white") }}
                {% if form.confirm_new_password.errors %}
                    {{ form.confirm_new_password(class="bg-gray-50 border-2 border-red-600 text-red-600 sm:text-sm rounded-lg focus:ring-red-900 focus:border-red-600 block w-full p-2.5") }}
                    <div class="text-red-600 mt-2">
                        {% for error in form.confirm_new_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_new_password(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500") }}
                {% endif %}
            </div>
            {{ form.submit(class="w-full cursor-pointer border border-blue-600 text-white bg-blue-600 hover:bg-transparent hover:text-blue-600 font-medium rounded-lg text-sm px-5 py-2.5 text-center hover:cursor dark:bg-blue-600 dark:hover:bg-transparent dark:hover:text-blue-700") }}
        </form>
    </div>
</div>
{% endblock content %}

website/templates/error.html
{% extends "base.html" %} 
{% block title %}Page Not Found{% endblock title %}
{% block content %}

<!-- ====== Error 404 Section Start -->
<section class="relative z-10 bg-primary py-[120px]">
    <div class="container mx-auto min-h-screen">
       <div class="-mx-4 flex">
          <div class="w-full px-4">
             <div class="mx-auto max-w-[400px] text-center">
                <h2
                   class="mb-2 text-[50px] font-bold leading-none text-white sm:text-[80px] md:text-[100px]"
                   >
                   404
                </h2>
                <h4
                   class="mb-3 text-[22px] font-semibold leading-tight text-white"
                   >
                   Oops! That page can't be found
                </h4>
                <p class="mb-8 text-lg text-white">
                   The page you are looking for is not accessible or does not exist
                </p>
                <a 
                   href="{{ url_for('main.home') }}"
                   class="mt-8 inline-block rounded-lg border border-white px-8 py-3 text-center text-base font-semibold text-white transition hover:bg-slate-950 hover:text-primary"
                   >
                Go To Home
                </a>
             </div>
          </div>
       </div>
    </div>
    <div
       class="absolute top-0 left-0 -z-10 flex h-full w-full items-center justify-between space-x-5 md:space-x-8 lg:space-x-14"
       >
       <div
          class="h-full w-1/3 bg-gradient-to-t from-[#FFFFFF14] to-[#C4C4C400]"
          ></div>
       <div class="flex h-full w-1/3">
          <div
             class="h-full w-1/2 bg-gradient-to-b from-[#FFFFFF14] to-[#C4C4C400]"
             ></div>
          <div
             class="h-full w-1/2 bg-gradient-to-t from-[#FFFFFF14] to-[#C4C4C400]"
             ></div>
       </div>
       <div
          class="h-full w-1/3 bg-gradient-to-b from-[#FFFFFF14] to-[#C4C4C400]"
          ></div>
    </div>
 </section>
 <!-- ====== Error 404 Section End -->

 {% endblock content %}

website/templates/profile.html
{% extends "base.html" %} 
{% block title %}Profile{% endblock title %}
{% block content %}
<div
  class="flex flex-col items-center justify-center px-6 py-20 mx-auto"
>
  <div
    class="w-full bg-white rounded-lg shadow-lg border border-gray-300 dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700"
  >
    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
      <div class="photo-wrapper p-2">
        <img class="w-32 h-32 rounded-full mx-auto" src="{{ image_file }}" />
      </div>
      <div class="p-2">
        <h2 class="text-center text-blue-500 text-2xl font-medium leading-8">
          {{ current_user.username }}
        </h2>
        <p class="text-center text-gray-400 text-lg font-semibold">
          {{ current_user.email }}
        </p>
      </div>

      <form
        method="POST"
        action=""
        class="space-y-4 md:space-y-6"
        enctype="multipart/form-data"
      >
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <div class="mb-4">
            {{ form.username.label(class="block mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} {% if form.username.errors %}
            {{ form.username(class="bg-gray-50 border-2 border-red-600
            text-red-600 sm:text-sm rounded-lg focus:ring-red-900
            focus:border-red-600 block w-full p-2.5") }}
            <div class="text-red-600 mt-2">
              {% for error in form.username.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.username(class="bg-gray-50 border
            border-gray-300 text-gray-900 sm:text-sm rounded-lg
            focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5
            dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400
            dark:text-white dark:focus:ring-blue-500
            dark:focus:border-blue-500") }} {% endif %}
          </div>
          <div class="mb-4">
            {{ form.email.label(class="block mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} {% if form.email.errors %} {{
            form.email(class="bg-gray-50 border-2 border-red-600 text-red-600
            sm:text-sm rounded-lg focus:ring-red-900 focus:border-red-600
            block w-full p-2.5") }}
            <div class="text-red-600 mt-2">
              {% for error in form.email.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.email(class="bg-gray-50 border border-gray-300
            text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600
            focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700
            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
            dark:focus:ring-blue-500 dark:focus:border-blue-500") }} {% endif
            %}
          </div>
          <div class="mb-4">
            {{ form.firstname.label(class="block mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} {% if form.firstname.errors %} {{
            form.firstname(class="bg-gray-50 border-2 border-red-600 text-red-600
            sm:text-sm rounded-lg focus:ring-red-900 focus:border-red-600
            block w-full p-2.5") }}
            <div class="text-red-600 mt-2">
              {% for error in form.firstname.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.firstname(class="bg-gray-50 border border-gray-300
            text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600
            focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700
            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
            dark:focus:ring-blue-500 dark:focus:border-blue-500") }} {% endif
            %}
          </div>
          <div class="mb-4">
            {{ form.lastname.label(class="block mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} {% if form.lastname.errors %} {{
            form.lastname(class="bg-gray-50 border-2 border-red-600 text-red-600
            sm:text-sm rounded-lg focus:ring-red-900 focus:border-red-600
            block w-full p-2.5") }}
            <div class="text-red-600 mt-2">
              {% for error in form.lastname.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.lastname(class="bg-gray-50 border border-gray-300
            text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600
            focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700
            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
            dark:focus:ring-blue-500 dark:focus:border-blue-500") }} {% endif
            %}
          </div>
          <div class="mb-4">
            {{ form.phone.label(class="block mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} {% if form.phone.errors %} {{
            form.phone(class="bg-gray-50 border-2 border-red-600 text-red-600
            sm:text-sm rounded-lg focus:ring-red-900 focus:border-red-600
            block w-full p-2.5") }}
            <div class="text-red-600 mt-2">
              {% for error in form.phone.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.phone(class="bg-gray-50 border border-gray-300
            text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600
            focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700
            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
            dark:focus:ring-blue-500 dark:focus:border-blue-500") }} {% endif
            %}
          </div>
          {% if current_user.ROLE == 'parent' %}
          <div class="mb-4">
            {{ form.ewallet_balance.label(class="block mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} 
            {{ form.ewallet_balance(class="bg-gray-50
            text-gray-900 sm:text-sm rounded-lg block w-full p-2.5 dark:bg-gray-700
            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white", readonly="readonly") }}
          </div>
          {% elif current_user.ROLE == 'student' %}
          <div class="mb-4">
            {{ form.status.label(class="block mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} 
            {{ form.status(class="bg-gray-50
            text-gray-900 sm:text-sm rounded-lg block w-full p-2.5 dark:bg-gray-700
            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white", readonly="readonly") }}
          </div>
          {% endif %}
          <div class="mb-4">
            {{ form.picture.label(class="block mt-2 mb-2 text-md font-medium
            text-gray-900 dark:text-white") }} 
            {{ form.picture(class="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }} 
            {% if form.picture.errors %} 
            {% for error in form.picture.errors %}
            <span class="text-red-600 mt-2">{{ error }}</span><br />
            {% endfor %} {% endif %}
          </div>
          {% if current_user.ROLE == 'student' %}
          <div class="relative overflow-x-auto my-10">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
              <thead class="text-xs text-white uppercase bg-blue-700">
                <tr>
                  <th scope="col" class="px-6 py-3">
                    Parent's first name
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Parent's last name
                  </th>
                </tr>
              </thead>
              <tbody>
                  {% for parent in parents %}
                  <tr class="bg-white text-blue-700 border-b">
                    <th scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
                      {{ parent.FIRST_NAME }} 
                    </th>
                    <td class="px-6 py-4 font-medium">
                      {{ parent.LAST_NAME }}
                    </td>
                  </tr>
                  {% endfor %}
                </tr>
              </tbody>
            </table>
          </div>
          {% elif current_user.ROLE == 'parent' %}
          <div class="relative overflow-x-auto my-10">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
              <thead class="text-xs text-white uppercase bg-blue-700">
                <tr>
                  <th scope="col" class="px-6 py-3">
                    Child's name
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for student in students %}
                  <tr class="bg-white text-blue-700 border-b">
                    <th scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
                      {{ student.LAST_NAME }} {{ student.FIRST_NAME }}
                    </th>
                    <td class="px-6 py-4 font-medium">
                      {{ student.STATUS }}
                    </td>
                  </tr>
                {% endfor %}
                </tr>
              </tbody>
            </table>
          </div>
          {% endif %}
        </fieldset>
        <div class="form-group flex-col space-y-5">
          <a href="{{ url_for('main.change_password') }}" class="w-full flex text-center justify-center cursor-pointer text-white bg-blue-600
          hover:bg-transparent hover:text-blue-600 focus:ring-2 focus:outline-none
          focus:ring-blue-300 border border-blue-600 font-medium rounded-lg text-sm py-2.5
          hover:cursor dark:bg-blue-600 dark:hover:bg-transparent
          dark:hover:text-blue-600">Change Password</a>
          {{ form.submit(class="w-full cursor-pointer text-white bg-blue-600
          hover:bg-transparent hover:text-blue-600 focus:ring-2 focus:outline-none
          focus:ring-blue-300 border border-blue-600 font-medium rounded-lg text-sm px-5 py-2.5
          text-center hover:cursor dark:bg-blue-600 dark:hover:bg-transparent
          dark:hover:text-blue-600") }}
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}